# This is a spack environment manifest file for GCHP dependencies using Intel compilers and Intel MPI.
# Preconditions: spack install gcc@8.5.0

spack:
  packages:
    all:
      target: [x86_64]
  specs:
    - cmake@3.13.5
    - libfabric@1.14.0 fabrics=sockets,tcp,udp,efa,mlx,shm
    - openmpi@3.0.5%gcc@8.5.0 +lustre +gpfs fabrics=auto
    - hdf5@1.8.10%gcc@8.5.0 -mpi -tools
    - netcdf-c@4.3.3%gcc@8.5.0
    - netcdf-fortran@4.4.3%gcc@8.5.0
    - esmf@8.0.0%gcc@8.5.0 -pnetcdf -xerces -pio
  concretization: together
