name: InstallBashDataCatalog
description: This component installs the bashdatacatalog
schemaVersion: 1.0

phases:
  - name: build
    steps:
      - name: Install
        action: ExecuteBash
        inputs:
          commands:
            - git clone https://github.com/LiamBindle/bashdatacatalog.git /opt/bashdatacatalog
            - echo 'export PATH=$PATH:/opt/bashdatacatalog' >> /etc/bashrc
